### PR TITLE
Add Google Map image

### PR DESCRIPTION
**Pull request by bstanger**
This work adds a Google Map image to the component.  A user can also click on the map to open another tab with the matching Google Maps link.  I also created some test with Jest, utilizing snapshots.

### CODE REVIEW

**Review by YZhenY — APPROVED** [review]
Looks good to go!!

**Review by YZhenY — COMMENTED** [review]
Trying to understand more with regards to snapshots:  
do you take a snapshot after coding out the map? what do you then use the snapshot to test?

**Review by gearycholera — APPROVED** [review]
Looks good to me! Making shallow, mount, and render global was really clever!

**Comment by bstanger** [comment]
Not sure I fully understand your question @YZhenY but maybe the flow chart in this article will answer your question - https://medium.com/@luisvieira_gmr/snapshot-testing-react-components-with-jest-3455d73932a4.  My understanding is that the snapshot is automatically created the first time I run the test because I have no existing snapshot and then any future tests I run will doublecheck that an outputted snapshot matches the one previously generated.

And I wish I could take credit for the cleverness @girikalra but honestly I copy-pasted from this article - https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f

**Pull request merged**
