### PR TITLE
Set Up Webpack Dev Middleware

### PR DESCRIPTION
**Pull request by bstanger**
I don't really understand what this is doing.  Supposedly it handles files in memory, but I believe on load of my module, it's still referencing the bundle.js file created previously.  But I'm not sure how to load the in memory files...  May ask an HiR or Anthony about it tomorrow.

### CODE REVIEW

**Comment by gearycholera** [comment]
Are all the cirleCI checks supposed to pass before we approve?

**Comment by bstanger** [comment]
@girikalra I don't think so because I just did the initial set up for adding CircleCI to my repo but haven't done any work yet to get tests to run as I expect and pass.  So I assume they will be broken for all my PRs until I finish integrating CircleCI.

**Review by gearycholera — APPROVED** [review]
Nice! I am still not totally sure how webpack middleware is supposed to work, but from what I've seen, this looks correct. Do you know is the publicPath is always supposed to be './' or does it change based on individual file structure and whatnot? Never really understood what PublicPath was supposed to point to

**Comment by bstanger** [comment]
@girikalra Yeah I have no idea about publicPath.  Honestly I just followed Zhen's lead with the './' value.  I wonder though if whatever I put there might conflict with my app.use line about express.static.  I'm gonna try to ask Anthony what those lines are doing...

**Pull request merged**
